name: Bygg pull request

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '**.MD'
      - '.gitignore'
      - 'LICENCE'
      - 'CODEOWNERS'
      - '.github/workflows/build.yml'
      - '.github/workflows/dispatch.yml'
      - '.github/workflows/codeql-analysis.yml'
      - '.github/workflows/release.yml'
      - '.github/dependabot.yml'
      - '.github/release-drafter.yml'
env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Bygger og tester
        run: |
          mvn install -e --batch-mode --settings .github/.m2/settings.xml
      - name: Sonar analyse
        if: github.actor != 'dependabot[bot]'
        run: |
          mvn jacoco:report org.sonarsource.scanner.maven:sonar-maven-plugin:sonar --settings .github/.m2/settings.xml
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
