
name: Bygg og deploy

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '**.MD'
      - '.gitignore'
      - 'LICENCE'
      - 'CODEOWNERS'
      - '.github/workflows/build-pr.yml'
      - '.github/workflows/dispatch.yml'
      - '.github/workflows/codeql-analysis.yml'
      - '.github/dependabot.yml'
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Bygg og  test
        run: |
          mvn install -e --batch-mode --settings .github/.m2/settings.xml
      - name: Release Drafter
        uses: release-drafter/release-drafter@v5
        if: success()
      - name: Sonar analyse
        run: |
          mvn jacoco:report org.sonarsource.scanner.maven:sonar-maven-plugin:sonar --settings .github/.m2/settings.xml
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
